
FAILURE: Build failed with an exception.

* Where:
Build file '/home/runner/work/TV/TV/src/app/build.gradle' line: 54

* What went wrong:
A problem occurred evaluating project ':app'.
> Cannot convert 'null' to File.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights from a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.GradleScriptException: 
